"""UI translations for the Streamlit dashboard."""

TRANSLATIONS = {
    "en": {
        "page_title": "Solai | Replenishment", "title": "Warehouse Replenishment",
        "intro": "Procurement recommendations will be prepared for manager review. This demo does not send orders to suppliers.",
        "language": "Language", "load_error": "Could not load sample data: {error}",
        "sales_rows": "Sales history rows", "skus": "SKUs", "suppliers": "Suppliers",
        "history_heading": "Sample sales history and inventory", "forecast_heading": "Demand Forecast",
        "forecast_caption": "Next-month demand in units/month. Baseline uses the latest six calendar months, falling back to older regular observations if needed. Missing months are not assumed to have zero sales.",
        "sku": "SKU", "historical_sales": "Historical sales", "sales_spike": "Sales spike",
        "recent_baseline": "Recent baseline", "next_forecast": "Next-month forecast", "month": "Month",
        "sales_units_month": "Sales (units/month)", "forecast_audit": "Forecast inputs and anomaly audit",
        "raw_mean": "Raw recent mean (including spikes): {value:.1f} units/month",
        "replenishment_heading": "Replenishment Recommendations",
        "replenishment_caption": "Proposals for manager review only. REVIEW takes priority over ORDER or COVERED when data needs attention; its calculated quantity is provisional. In-transit stock is assumed to arrive within the lead-time horizon.",
        "service_factor": "Safety-stock service-level factor",
        "service_help": "Safety stock = factor × monthly demand standard deviation × sqrt(lead-time days / 30). This is an approximation from monthly data, not a guaranteed service level.",
        "skus_order": "SKUs requiring order", "units_recommended": "Total units recommended",
        "skus_covered": "SKUs covered by existing inventory", "skus_review": "SKUs requiring review",
        "count_caption": "Order counts and units include provisional positive quantities marked REVIEW. Covered counts include only COVERED rows. Uncalculable quantities are shown as blank. Orange rows require an order; yellow rows require review.",
        "inventory_chart": "Inventory and target stock by SKU", "units": "Units", "stock_measure": "Stock measure",
        "quantity_chart": "Recommended order quantity by SKU", "units_to_order": "Units to order",
        "supplier_heading": "Supplier proposals — manager review only",
        "supplier_caption": "Estimated values use each SKU's latest unit_price, assuming a common currency. Taxes, shipping, pack sizes and minimum order quantities are not included. A missing price leaves the supplier total value unknown.",
        "no_proposals": "No positive order quantities are currently proposed. Check any REVIEW rows above.",
        "proposed_units": "{supplier} — {quantity} proposed units", "why_order": "Why this order?",
        "calculation": "Calculation", "value": "Value", "unknown_supplier": "Unknown supplier",
        "status_ORDER": "ORDER", "status_COVERED": "COVERED", "status_REVIEW": "REVIEW",
        "selected_product": "Product: {name}. ",
        "stock_current_stock": "Current stock", "stock_in_transit": "In transit", "stock_target_stock": "Target stock",
        "col_date": "Date", "col_sku": "SKU", "col_product_name": "Product name", "col_category": "Category", "col_supplier": "Supplier", "col_sales": "Sales", "col_current_stock": "Current stock", "col_in_transit": "In transit", "col_lead_time_days": "Lead time (days)", "col_unit_price": "Unit price", "col_is_anomaly": "Is anomaly", "col_anomaly_reason": "Anomaly reason", "col_anomaly_threshold": "Anomaly threshold",
        "col_baseline_demand": "Baseline demand", "col_seasonal_factor": "Seasonal factor", "col_forecast_demand": "Forecast demand", "col_anomalies_detected": "Anomalies detected", "col_raw_demand_estimate": "Raw demand estimate", "col_forecast_month": "Forecast month", "col_seasonal_source": "Seasonal source", "col_baseline_observations": "Baseline observations", "col_baseline_anomalies_excluded": "Baseline anomalies excluded", "col_lead_time_demand": "Lead-time demand", "col_safety_stock": "Safety stock", "col_inventory_position": "Inventory position", "col_target_stock": "Target stock", "col_recommended_order_qty": "Recommended order qty", "col_status": "Status", "col_daily_demand": "Daily demand", "col_monthly_demand_std": "Monthly demand std", "col_service_level_factor": "Service-level factor", "col_history_observations": "History observations", "col_anomalies_excluded": "Anomalies excluded", "col_review_reasons": "Review reasons", "col_estimated_order_value": "Estimated order value", "col_skus_to_order": "SKUs to order", "col_total_units": "Total units", "col_skus_requiring_review": "SKUs requiring review", "col_raw_order_qty": "Raw order qty", "col_safety_stock_method": "Safety-stock method",
        "ex_f1": "Regular demand is the median of {n} non-anomalous monthly observations: {value:.1f} units. {excluded} unusual sales spike(s) were excluded from the recent baseline calculation and retained in the audit history. ",
        "ex_no_season": "There is insufficient reliable seasonal history; the seasonal factor is 1.00. ",
        "ex_season": "Seasonality from {source} history {direction} the forecast by {change:.1f}% relative to recent months. ",
        "direction_up": "increases", "direction_down": "decreases", "ex_forecast": "Forecast for {month}: {value:.1f} units. The final decision remains with the manager.",
        "ex_r1": "Forecast demand is {value} units/month.", "ex_daily": "Daily demand is forecast / 30 = {daily:.2f} units/day. Supplier lead time is {days} days, requiring {daily:.2f} × {days} = {lead:.2f} units during lead time.",
        "ex_safety": "Safety stock is {factor:.2f} × {std:.2f} × sqrt({days} / 30) = {stock:.2f} units. The monthly variability estimate uses {n} non-anomalous observations; greater variability increases safety stock.",
        "ex_inventory": "Current stock is {current} units and {transit} units are in transit, giving an inventory position of {position:.2f}. Target stock is {lead:.2f} + {safety:.2f} = {target:.2f}. Raw need is {target:.2f} − {position:.2f} = {raw:.2f}. The recommended replenishment quantity is {qty} units (raw need rounded up, with a minimum of zero). Calculations use unrounded values.",
        "ex_zero": "No order is recommended because current stock plus in-transit inventory meets or exceeds target stock.",
        "ex_unavailable": "A reliable order quantity cannot be calculated from the supplied inputs; no quantity is proposed.",
        "ex_fallback": "Insufficient-history fallback: fewer than three clean monthly observations are available. Monthly variability is set to the larger of forecast demand and the clean historical mean (a conservative 100% variability assumption). Manager review is required.",
        "ex_anomaly": "{detected} sales anomaly/anomalies were detected by Phase 1; {excluded} flagged observation(s) in the variability window were excluded from safety-stock estimation and retained for audit.",
        "ex_seasonal_applied": "Phase 1 already applied a seasonal factor of {factor:.4f} to demand; it is not applied again here.",
        "ex_review": "REVIEW required: {reasons}. Any calculated quantity is provisional.", "ex_proposal": "This is a proposal for manager review only. No supplier order is sent.",
    },
    "ru": {
        "page_title": "Solai | Пополнение запасов", "title": "Пополнение складских запасов",
        "intro": "Рекомендации по закупкам подготовлены для проверки менеджером. В демоверсии заказы поставщикам не отправляются.", "language": "Язык", "load_error": "Не удалось загрузить пример данных: {error}",
        "sales_rows": "Строк истории продаж", "skus": "Артикулы", "suppliers": "Поставщики", "history_heading": "История продаж и запасы (пример)", "forecast_heading": "Прогноз спроса",
        "forecast_caption": "Спрос на следующий месяц, шт./месяц. Базовый уровень рассчитан по последним шести календарным месяцам; при необходимости используются более ранние обычные наблюдения. Пропущенные месяцы не считаются месяцами с нулевыми продажами.",
        "sku": "Артикул", "historical_sales": "Исторические продажи", "sales_spike": "Всплеск продаж", "recent_baseline": "Недавний базовый уровень", "next_forecast": "Прогноз на следующий месяц", "month": "Месяц", "sales_units_month": "Продажи (шт./месяц)", "forecast_audit": "Входные данные прогноза и проверка аномалий", "raw_mean": "Среднее недавних продаж (включая всплески): {value:.1f} шт./месяц",
        "replenishment_heading": "Рекомендации по пополнению", "replenishment_caption": "Предложения предназначены для проверки менеджером. Если данные требуют внимания, статус ПРОВЕРИТЬ имеет приоритет над статусами ЗАКАЗАТЬ и ПОКРЫТО; рассчитанное количество предварительное. Считается, что товар в пути прибудет в пределах срока поставки.", "service_factor": "Коэффициент уровня обслуживания для страхового запаса", "service_help": "Страховой запас = коэффициент × стандартное отклонение месячного спроса × sqrt(срок поставки в днях / 30). Это приближение по месячным данным, а не гарантированный уровень обслуживания.",
        "skus_order": "Артикулы, требующие заказа", "units_recommended": "Всего рекомендовано единиц", "skus_covered": "Артикулы, покрытые текущими запасами", "skus_review": "Артикулы, требующие проверки", "count_caption": "В число заказов и единиц входят предварительные положительные количества со статусом ПРОВЕРИТЬ. В покрытие входят только строки со статусом ПОКРЫТО. Нерассчитываемые количества показаны пустыми. Оранжевые строки требуют заказа, жёлтые — проверки.",
        "inventory_chart": "Запасы и целевой запас по артикулам", "units": "Единицы", "stock_measure": "Показатель запаса", "quantity_chart": "Рекомендуемое количество заказа по артикулам", "units_to_order": "Количество для заказа", "supplier_heading": "Предложения поставщикам — на проверку менеджеру", "supplier_caption": "Оценка рассчитана по последней цене единицы товара и предполагает единую валюту. Налоги, доставка, размеры упаковок и минимальные объёмы заказа не учитываются. Если цена отсутствует, общая стоимость для поставщика неизвестна.", "no_proposals": "Положительных количеств для заказа пока нет. Проверьте строки со статусом ПРОВЕРИТЬ выше.", "proposed_units": "{supplier} — предложено единиц: {quantity}", "why_order": "Почему этот заказ?", "calculation": "Расчёт", "value": "Значение", "unknown_supplier": "Неизвестный поставщик",
        "status_ORDER": "ЗАКАЗАТЬ", "status_COVERED": "ПОКРЫТО", "status_REVIEW": "ПРОВЕРИТЬ",
        "selected_product": "Товар: {name}. ",
        "selected_product": "Товар: {name}. ",
        "stock_current_stock": "Текущий запас", "stock_in_transit": "В пути", "stock_target_stock": "Целевой запас",
        "stock_current_stock": "Текущий запас", "stock_in_transit": "В пути", "stock_target_stock": "Целевой запас",
        "col_date": "Дата", "col_sku": "Артикул", "col_product_name": "Название товара", "col_category": "Категория", "col_supplier": "Поставщик", "col_sales": "Продажи", "col_current_stock": "Текущий запас", "col_in_transit": "В пути", "col_lead_time_days": "Срок поставки (дни)", "col_unit_price": "Цена за единицу", "col_is_anomaly": "Аномалия", "col_anomaly_reason": "Причина аномалии", "col_anomaly_threshold": "Порог аномалии",
        "col_baseline_demand": "Базовый спрос", "col_seasonal_factor": "Сезонный коэффициент", "col_forecast_demand": "Прогноз спроса", "col_anomalies_detected": "Обнаружено аномалий", "col_raw_demand_estimate": "Исходная оценка спроса", "col_forecast_month": "Месяц прогноза", "col_seasonal_source": "Источник сезонности", "col_baseline_observations": "Наблюдения для базы", "col_baseline_anomalies_excluded": "Исключено аномалий из базы", "col_lead_time_demand": "Спрос за срок поставки", "col_safety_stock": "Страховой запас", "col_inventory_position": "Позиция запаса", "col_target_stock": "Целевой запас", "col_recommended_order_qty": "Рекомендуемое количество заказа", "col_status": "Статус", "col_daily_demand": "Суточный спрос", "col_monthly_demand_std": "Стандартное отклонение месячного спроса", "col_service_level_factor": "Коэффициент обслуживания", "col_history_observations": "Исторические наблюдения", "col_anomalies_excluded": "Исключено аномалий", "col_review_reasons": "Причины проверки", "col_estimated_order_value": "Оценочная стоимость заказа", "col_skus_to_order": "Артикулы к заказу", "col_total_units": "Всего единиц", "col_skus_requiring_review": "Артикулы для проверки", "col_raw_order_qty": "Исходная потребность в заказе", "col_safety_stock_method": "Метод расчёта страхового запаса",
        "ex_f1": "Обычный спрос — медиана по {n} месячным наблюдениям без аномалий: {value:.1f} шт. Из недавнего базового расчёта исключены необычные всплески продаж ({excluded}), они сохранены в истории аудита. ", "ex_no_season": "Надёжной сезонной истории недостаточно; сезонный коэффициент равен 1,00. ", "ex_season": "Сезонность по истории «{source}» {direction} прогноз на {change:.1f}% относительно недавних месяцев. ", "direction_up": "увеличивает", "direction_down": "уменьшает", "ex_forecast": "Прогноз на {month}: {value:.1f} шт. Окончательное решение принимает менеджер.",
        "ex_r1": "Прогноз спроса: {value} шт./месяц.", "ex_daily": "Суточный спрос = прогноз / 30 = {daily:.2f} шт./день. Срок поставки — {days} дн.; спрос за этот срок: {daily:.2f} × {days} = {lead:.2f} шт.", "ex_safety": "Страховой запас = {factor:.2f} × {std:.2f} × sqrt({days} / 30) = {stock:.2f} шт. Оценка месячной вариативности использует {n} наблюдений без аномалий; большая вариативность увеличивает страховой запас.", "ex_inventory": "Текущий запас — {current} шт., в пути — {transit} шт.; позиция запаса составляет {position:.2f}. Целевой запас: {lead:.2f} + {safety:.2f} = {target:.2f}. Исходная потребность: {target:.2f} − {position:.2f} = {raw:.2f}. Рекомендуемое количество пополнения — {qty} шт. (исходная потребность округлена вверх, минимум — ноль). В расчётах используются неокруглённые значения.", "ex_zero": "Заказ не требуется: текущего запаса и товара в пути достаточно для достижения целевого запаса.", "ex_unavailable": "Нельзя надёжно рассчитать количество заказа по предоставленным данным; количество не предлагается.", "ex_fallback": "Резервный расчёт при недостатке истории: доступно менее трёх чистых месячных наблюдений. Месячная вариативность принята равной большему из прогноза спроса и среднего по чистой истории (консервативное допущение о вариативности 100%). Требуется проверка менеджером.", "ex_anomaly": "На первом этапе обнаружено аномалий продаж: {detected}; помеченных наблюдений в окне вариативности исключено из оценки страхового запаса: {excluded}. Они сохранены для аудита.", "ex_seasonal_applied": "На первом этапе к спросу уже применён сезонный коэффициент {factor:.4f}; повторно он не применяется.", "ex_review": "Требуется проверка: {reasons}. Рассчитанное количество предварительное.", "ex_proposal": "Это предложение для проверки менеджером. Заказ поставщику не отправляется.",
    },
    "kz": {
        "page_title": "Solai | Қорды толықтыру", "title": "Қойма қорын толықтыру",
        "intro": "Сатып алу ұсыныстары менеджердің тексеруіне дайындалады. Бұл демо жеткізушілерге тапсырыс жібермейді.", "language": "Тіл", "load_error": "Үлгі деректерін жүктеу мүмкін болмады: {error}", "sales_rows": "Сату тарихының жолдары", "skus": "Артикулдар", "suppliers": "Жеткізушілер", "history_heading": "Сату тарихы мен қор үлгісі", "forecast_heading": "Сұраныс болжамы",
        "forecast_caption": "Келесі айдағы сұраныс, дана/ай. Негізгі деңгей соңғы алты күнтізбелік ай бойынша есептеледі; қажет болса, бұрынғы қалыпты бақылаулар алынады. Бос айлар нөлдік сатылым деп есептелмейді.", "sku": "Артикул", "historical_sales": "Тарихи сатылым", "sales_spike": "Сатылымның күрт өсуі", "recent_baseline": "Соңғы негізгі деңгей", "next_forecast": "Келесі ай болжамы", "month": "Ай", "sales_units_month": "Сатылым (дана/ай)", "forecast_audit": "Болжам деректері және ауытқулар аудиті", "raw_mean": "Соңғы сатылымның орташа мәні (күрт өсулерді қоса): {value:.1f} дана/ай",
        "replenishment_heading": "Қорды толықтыру ұсыныстары", "replenishment_caption": "Ұсыныстар менеджердің тексеруіне арналған. Деректерді тексеру қажет болса, ТЕКСЕРУ мәртебесі ТАПСЫРЫС БЕРУ не ҚАМТАМАСЫЗ ЕТІЛГЕН мәртебесінен басым; есептелген сан алдын ала берілген. Жолдағы қор жеткізу мерзімі ішінде келеді деп есептеледі.", "service_factor": "Сақтандыру қорының қызмет көрсету деңгейі коэффициенті", "service_help": "Сақтандыру қоры = коэффициент × айлық сұраныстың стандартты ауытқуы × sqrt(жеткізу мерзімі (күн) / 30). Бұл айлық деректерге негізделген жуықтау, кепілді қызмет деңгейі емес.", "skus_order": "Тапсырыс қажет артикулдар", "units_recommended": "Ұсынылған жалпы дана", "skus_covered": "Қолдағы қор жеткілікті артикулдар", "skus_review": "Тексеру қажет артикулдар", "count_caption": "Тапсырыс пен дана санына ТЕКСЕРУ мәртебесі бар алдын ала оң мөлшерлер кіреді. Қамтамасыз етілгендер санына тек ҚАМТАМАСЫЗ ЕТІЛГЕН жолдары кіреді. Есептелмейтін мөлшерлер бос көрсетіледі. Қызғылт сары жолдар тапсырысты, сары жолдар тексеруді қажет етеді.",
        "inventory_chart": "Артикул бойынша қор және мақсатты қор", "units": "Дана", "stock_measure": "Қор көрсеткіші", "quantity_chart": "Артикул бойынша ұсынылған тапсырыс саны", "units_to_order": "Тапсырысқа арналған дана", "supplier_heading": "Жеткізушілерге ұсыныстар — менеджер тексеруі үшін", "supplier_caption": "Бағалау әр артикулдың соңғы бірлік бағасына негізделіп, ортақ валюта деп есептейді. Салық, жеткізу, қаптама өлшемі және ең аз тапсырыс саны есепке алынбайды. Баға болмаса, жеткізуші бойынша жалпы құн белгісіз.", "no_proposals": "Қазір тапсырысқа оң мөлшер ұсынылмады. Жоғарыдағы ТЕКСЕРУ жолдарын қараңыз.", "proposed_units": "{supplier} — ұсынылған дана саны: {quantity}", "why_order": "Бұл тапсырыс не үшін ұсынылды?", "calculation": "Есептеу", "value": "Мәні", "unknown_supplier": "Белгісіз жеткізуші", "status_ORDER": "ТАПСЫРЫС БЕРУ", "status_COVERED": "ҚАМТАМАСЫЗ ЕТІЛГЕН", "status_REVIEW": "ТЕКСЕРУ", "stock_current_stock": "Ағымдағы қор", "stock_in_transit": "Жолда", "stock_target_stock": "Мақсатты қор", "selected_product": "Тауар: {name}. ",
        "col_date": "Күні", "col_sku": "Артикул", "col_product_name": "Тауар атауы", "col_category": "Санат", "col_supplier": "Жеткізуші", "col_sales": "Сатылым", "col_current_stock": "Ағымдағы қор", "col_in_transit": "Жолдағы қор", "col_lead_time_days": "Жеткізу мерзімі (күн)", "col_unit_price": "Бірлік бағасы", "col_is_anomaly": "Ауытқу ма", "col_anomaly_reason": "Ауытқу себебі", "col_anomaly_threshold": "Ауытқу шегі", "col_baseline_demand": "Негізгі сұраныс", "col_seasonal_factor": "Маусымдық коэффициент", "col_forecast_demand": "Сұраныс болжамы", "col_anomalies_detected": "Анықталған ауытқулар", "col_raw_demand_estimate": "Сұраныстың бастапқы бағасы", "col_forecast_month": "Болжам айы", "col_seasonal_source": "Маусымдылық дереккөзі", "col_baseline_observations": "Негізгі бақылаулар", "col_baseline_anomalies_excluded": "Негізгі есептен алынған ауытқулар", "col_lead_time_demand": "Жеткізу мерзіміндегі сұраныс", "col_safety_stock": "Сақтандыру қоры", "col_inventory_position": "Қор позициясы", "col_target_stock": "Мақсатты қор", "col_recommended_order_qty": "Ұсынылған тапсырыс саны", "col_status": "Мәртебе", "col_daily_demand": "Күндік сұраныс", "col_monthly_demand_std": "Айлық сұраныстың стандартты ауытқуы", "col_service_level_factor": "Қызмет деңгейінің коэффициенті", "col_history_observations": "Тарихи бақылаулар", "col_anomalies_excluded": "Алынған ауытқулар", "col_review_reasons": "Тексеру себептері", "col_estimated_order_value": "Тапсырыстың болжамды құны", "col_skus_to_order": "Тапсырысқа артикулдар", "col_total_units": "Жалпы дана", "col_skus_requiring_review": "Тексеруді қажет ететін артикулдар", "col_raw_order_qty": "Тапсырыстың бастапқы қажеттілігі", "col_safety_stock_method": "Сақтандыру қорын есептеу әдісі",
        "ex_f1": "Қалыпты сұраныс — ауытқусыз {n} айлық бақылаудың медианасы: {value:.1f} дана. Соңғы негізгі есептен әдеттен тыс сатылым өсулері алынды ({excluded}), олар аудит тарихында сақталған. ", "ex_no_season": "Сенімді маусымдық тарих жеткіліксіз; маусымдық коэффициент 1.00. ", "ex_season": "«{source}» тарихындағы маусымдылық соңғы айлармен салыстырғанда болжамды {change:.1f}% {direction}. ", "direction_up": "арттырады", "direction_down": "төмендетеді", "ex_forecast": "{month} айының болжамы: {value:.1f} дана. Соңғы шешімді менеджер қабылдайды.",
        "ex_r1": "Болжамды сұраныс: {value} дана/ай.", "ex_daily": "Күндік сұраныс = болжам / 30 = {daily:.2f} дана/күн. Жеткізу мерзімі — {days} күн; осы мерзімдегі сұраныс: {daily:.2f} × {days} = {lead:.2f} дана.", "ex_safety": "Сақтандыру қоры = {factor:.2f} × {std:.2f} × sqrt({days} / 30) = {stock:.2f} дана. Айлық өзгермелілік бағасы ауытқусыз {n} бақылауды пайдаланады; өзгермелілік артса, сақтандыру қоры да өседі.", "ex_inventory": "Ағымдағы қор — {current} дана, жолда — {transit} дана; қор позициясы {position:.2f}. Мақсатты қор: {lead:.2f} + {safety:.2f} = {target:.2f}. Бастапқы қажеттілік: {target:.2f} − {position:.2f} = {raw:.2f}. Ұсынылған толықтыру саны — {qty} дана (бастапқы қажеттілік жоғары қарай дөңгелектеледі, ең азы — нөл). Есептеуде дөңгелектелмеген мәндер қолданылады.", "ex_zero": "Тапсырыс ұсынылмайды: ағымдағы және жолдағы қор мақсатты қорға жетеді немесе одан асады.", "ex_unavailable": "Берілген деректер бойынша тапсырыс санын сенімді есептеу мүмкін емес; сан ұсынылмайды.", "ex_fallback": "Тарих жеткіліксіз болғандағы қосалқы есеп: ауытқусыз үш айлық бақылаудан аз. Айлық өзгермелілік болжамды сұраныс пен қалыпты тарихтың орташа мәнінің үлкеніне тең деп алынды (сақтық үшін 100% өзгермелілік жорамалы). Менеджер тексеруі қажет.", "ex_anomaly": "1-кезеңде {detected} сатылым ауытқуы анықталды; өзгермелілік аралығындағы белгіленген {excluded} бақылау сақтандыру қорын есептеуден алынып, аудит үшін сақталды.", "ex_seasonal_applied": "1-кезеңде сұранысқа {factor:.4f} маусымдық коэффициенті қолданылған; ол мұнда қайта қолданылмайды.", "ex_review": "ТЕКСЕРУ қажет: {reasons}. Есептелген мөлшер алдын ала берілген.", "ex_proposal": "Бұл — менеджер тексеруіне арналған ұсыныс. Жеткізушіге тапсырыс жіберілмейді.",
    },
}


# Explanations added with the newer stockout and growth forecast logic.
TRANSLATIONS["en"].update({
    "ex_stockout": "Raw-sales baseline after robust spike handling: {sales:.1f} units. Stockout compensation adds {adjustment:.1f} units; {periods} stockout period(s) imply {lost:.1f} estimated lost units across history. ",
    "ex_stockout_review": "Stockout estimates need review: {unresolved} unresolved and {fallback} using limited-history fallback. ",
    "ex_stockout_missing": "Some stockout metadata is unavailable; no stockout was inferred for those rows. ",
    "ex_growth": "Sustainable growth is supported by {n} clean months. It increases the seasonal forecast by {change:.1f}% ({adjustment:.1f} units; uplift capped at 50%). ",
    "ex_no_growth": "No growth uplift applied: {reason}. ",
    "ex_stockout_excluded": "{n} stockout period(s) were excluded from safety-stock variability; imputed demand is not treated as observed variability.",
})
TRANSLATIONS["ru"].update({
    "ex_stockout": "Базовый уровень продаж после обработки всплесков: {sales:.1f} ед. Компенсация дефицита добавляет {adjustment:.1f} ед.; {periods} периода дефицита соответствуют оценке потерянного спроса {lost:.1f} ед. ",
    "ex_stockout_review": "Оценки дефицита требуют проверки: не разрешено {unresolved}, резервный расчёт по ограниченной истории — {fallback}. ",
    "ex_stockout_missing": "Для части строк метаданные дефицита отсутствуют; дефицит для них не предполагался. ",
    "ex_growth": "Устойчивый рост подтверждают {n} чистых месяцев. Он увеличивает сезонный прогноз на {change:.1f}% ({adjustment:.1f} ед.; максимум 50%). ",
    "ex_no_growth": "Поправка на рост не применена: {reason}. ",
    "ex_stockout_excluded": "Периоды дефицита ({n}) исключены из оценки вариативности страхового запаса; расчётный спрос не считается наблюдаемой вариативностью.",
})
TRANSLATIONS["kz"].update({
    "ex_stockout": "Күрт ауытқулар өңделгеннен кейінгі сатылым негізі: {sales:.1f} дана. Тапшылық өтемі {adjustment:.1f} дана қосады; {periods} тапшылық кезеңіндегі жоғалған сұраныс {lost:.1f} дана деп бағаланды. ",
    "ex_stockout_review": "Тапшылық бағаларын тексеру керек: шешілмегені — {unresolved}, шектеулі тарих бойынша қосалқы есеп — {fallback}. ",
    "ex_stockout_missing": "Кей жолдарда тапшылық метадеректері жоқ; олар үшін тапшылық болжанбады. ",
    "ex_growth": "Тұрақты өсімді {n} таза ай растайды. Ол маусымдық болжамды {change:.1f}% ({adjustment:.1f} дана; ең көбі 50%) арттырады. ",
    "ex_no_growth": "Өсу түзетуі қолданылмады: {reason}. ",
    "ex_stockout_excluded": "{n} тапшылық кезеңі сақтандыру қорын есептеудегі ауытқудан шығарылды; есептелген сұраныс нақты байқалған ауытқу саналмайды.",
})


def t(key: str) -> str:
    """Translate a UI key using the language in Streamlit session state."""
    import streamlit as st

    language = st.session_state.get("language", "en")
    return TRANSLATIONS.get(language, TRANSLATIONS["en"]).get(key, key)


def translated_frame(frame, status_values=False):
    """Return a display-only copy with localized headers and optional statuses."""
    from src.product_translator import translate_product_names

    result = frame.copy()
    if "product_name" in result.columns:
        language = __import__("streamlit").session_state.get("language", "en")
        names = translate_product_names(result["product_name"].dropna().unique(), language)
        result["product_name"] = result["product_name"].map(
            lambda value: names.get(str(value).strip(), value)
        )
    result.columns = [t(f"col_{column}") for column in result.columns]
    if status_values and "Status" in result.columns:
        result["Status"] = result["Status"].map(
            lambda value: t(f"status_{value}") if value in {"ORDER", "COVERED", "REVIEW"} else value
        )
    return result
